// src/lib/staticProducts.ts — Real product data with actual images (API fallback)

export interface StaticProduct {
  id: string; slug: string; name: string; shortDescription: string
  price: number; compareAtPrice?: number; primaryImage: string
  isFeatured: boolean
  category: { name: string; slug: string }
  brand: { name: string; slug: string }
  tags: string[]
  variants?: { id: string; name: string; shadeHex: string }[]
}

// ── MAKEUP ────────────────────────────────────────────────────────────────────
export const MAKEUP_PRODUCTS: StaticProduct[] = [
  {
    id: 'fenty-pro-filtr', slug: 'fenty-pro-filtr-foundation',
    name: "Pro Filt'r Soft Matte Foundation",
    shortDescription: 'Oil-free soft matte foundation — 50 inclusive shades',
    price: 40.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2096649-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Fenty Beauty', slug: 'fenty-beauty' },
    tags: ['foundation', 'matte', 'inclusive', 'bestseller'],
    variants: [
      { id: 'v1', name: '100W', shadeHex: '#F5E6D3' }, { id: 'v2', name: '185N', shadeHex: '#E8C99A' },
      { id: 'v3', name: '240W', shadeHex: '#C8956C' }, { id: 'v4', name: '360W', shadeHex: '#8B5E3C' },
      { id: 'v5', name: '490N', shadeHex: '#3D1C0A' },
    ],
  },
  {
    id: 'rare-soft-pinch-blush', slug: 'rare-soft-pinch-liquid-blush',
    name: 'Soft Pinch Liquid Blush',
    shortDescription: 'Highly pigmented 2-drop liquid blush',
    price: 22.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2516028-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Rare Beauty', slug: 'rare-beauty' },
    tags: ['blush', 'liquid', 'viral', 'pigmented'],
    variants: [
      { id: 'v1', name: 'Joy', shadeHex: '#E8A0A0' }, { id: 'v2', name: 'Hope', shadeHex: '#D4698A' },
      { id: 'v3', name: 'Bliss', shadeHex: '#C1694F' }, { id: 'v4', name: 'Serenity', shadeHex: '#B07080' },
    ],
  },
  {
    id: 'ct-matte-revolution', slug: 'charlotte-tilbury-matte-revolution',
    name: 'Matte Revolution Lipstick',
    shortDescription: 'Iconic 12-hour velvet-matte lipstick',
    price: 34.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s1617696-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Charlotte Tilbury', slug: 'charlotte-tilbury' },
    tags: ['lipstick', 'matte', 'long-wear', 'bestseller'],
    variants: [
      { id: 'v1', name: 'Pillow Talk', shadeHex: '#C9706A' },
      { id: 'v2', name: 'Red Carpet Red', shadeHex: '#C41E3A' },
      { id: 'v3', name: 'Bond Girl', shadeHex: '#8B1A4A' },
    ],
  },
  {
    id: 'nars-radiant-concealer', slug: 'nars-radiant-creamy-concealer',
    name: 'Radiant Creamy Concealer',
    shortDescription: 'Brightening concealer with a radiant finish',
    price: 32.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s1629600-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'NARS', slug: 'nars' },
    tags: ['concealer', 'brightening', 'radiant', 'bestseller'],
    variants: [
      { id: 'v1', name: 'Chantilly', shadeHex: '#F5E6D3' },
      { id: 'v2', name: 'Vanilla', shadeHex: '#EDD5B8' },
      { id: 'v3', name: 'Custard', shadeHex: '#D9B99B' },
    ],
  },
  {
    id: 'pgm-mattetrance', slug: 'pat-mcgrath-mattetrance',
    name: 'MatteTrance Lipstick',
    shortDescription: 'Ultra-pigmented editorial matte lipstick',
    price: 45.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2001562-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Pat McGrath Labs', slug: 'pat-mcgrath-labs' },
    tags: ['lipstick', 'matte', 'luxury', 'editorial'],
    variants: [
      { id: 'v1', name: 'Elson 5', shadeHex: '#C41E3A' },
      { id: 'v2', name: 'Omi', shadeHex: '#8B1A4A' },
      { id: 'v3', name: 'Flesh 3', shadeHex: '#D4808E' },
    ],
  },
  {
    id: 'ct-flawless-filter', slug: 'charlotte-tilbury-flawless-filter',
    name: 'Flawless Filter',
    shortDescription: 'Award-winning complexion booster & primer',
    price: 49.00, compareAtPrice: 58.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2282832-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Charlotte Tilbury', slug: 'charlotte-tilbury' },
    tags: ['primer', 'highlighter', 'glow', 'bestseller'],
    variants: [
      { id: 'v1', name: '1 Fair', shadeHex: '#F5E6D3' },
      { id: 'v2', name: '3 Light', shadeHex: '#E8C99A' },
      { id: 'v3', name: '5 Medium', shadeHex: '#C8956C' },
    ],
  },
  {
    id: 'ysl-rouge-pur-couture', slug: 'ysl-rouge-pur-couture',
    name: 'Rouge Pur Couture Lipstick',
    shortDescription: 'YSL iconic satin lipstick',
    price: 40.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2751402-main-zoom.jpg',
    isFeatured: false,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'YSL Beauty', slug: 'ysl-beauty' },
    tags: ['lipstick', 'satin', 'luxury', 'iconic'],
    variants: [
      { id: 'v1', name: 'R1 Le Rouge', shadeHex: '#C41E3A' },
      { id: 'v2', name: 'N1 Nude Beige', shadeHex: '#D4808E' },
      { id: 'v3', name: 'R7 Fuchsia', shadeHex: '#C2185B' },
    ],
  },
  {
    id: 'mac-ruby-woo', slug: 'mac-ruby-woo-lipstick',
    name: 'Retro Matte Lipstick — Ruby Woo',
    shortDescription: 'The iconic MAC red — vivid matte finish',
    price: 22.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s1606219-main-zoom.jpg',
    isFeatured: false,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'MAC', slug: 'mac' },
    tags: ['lipstick', 'matte', 'iconic', 'red'],
    variants: [
      { id: 'v1', name: 'Ruby Woo', shadeHex: '#C41E3A' },
      { id: 'v2', name: 'Chili', shadeHex: '#9B4448' },
      { id: 'v3', name: 'Velvet Teddy', shadeHex: '#B07060' },
    ],
  },
  {
    id: 'dior-backstage-foundation', slug: 'dior-backstage-foundation',
    name: 'Backstage Face & Body Foundation',
    shortDescription: 'Natural glow buildable foundation — face & body',
    price: 52.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2282835-main-zoom.jpg',
    isFeatured: false,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Dior Beauty', slug: 'dior-beauty' },
    tags: ['foundation', 'luminous', 'buildable', 'natural'],
    variants: [
      { id: 'v1', name: '0N', shadeHex: '#F5E6D3' }, { id: 'v2', name: '1N', shadeHex: '#EDD5B8' },
      { id: 'v3', name: '2N', shadeHex: '#D9B99B' }, { id: 'v4', name: '4N', shadeHex: '#A0663C' },
    ],
  },
  {
    id: 'fenty-snap-shadows', slug: 'fenty-snap-shadows',
    name: 'Snap Shadows Mix & Match Palette',
    shortDescription: 'Six-shade magnetic snap eyeshadow palette',
    price: 29.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2096650-main-zoom.jpg',
    isFeatured: false,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Fenty Beauty', slug: 'fenty-beauty' },
    tags: ['eyeshadow', 'palette', 'metallic', 'affordable'],
  },
  {
    id: 'pgm-mothership', slug: 'pgm-mothership-palette',
    name: 'Mothership VI Eyeshadow Palette',
    shortDescription: 'Iconic 10-shade palette with transcendent pigments',
    price: 125.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2001563-main-zoom.jpg',
    isFeatured: true,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Pat McGrath Labs', slug: 'pat-mcgrath-labs' },
    tags: ['eyeshadow', 'palette', 'luxury', 'editorial', 'metallic'],
  },
  {
    id: 'dior-mascara', slug: 'dior-diorshow-mascara',
    name: 'Diorshow Iconic Overcurl Mascara',
    shortDescription: 'Extreme volume and curl professional mascara',
    price: 32.00,
    primaryImage: 'https://www.sephora.com/productimages/sku/s2282836-main-zoom.jpg',
    isFeatured: false,
    category: { name: 'Makeup', slug: 'makeup' },
    brand: { name: 'Dior Beauty', slug: 'dior-beauty' },
    tags: ['mascara', 'volume', 'curl', 'longwear'],
  },
]
