-- Fragrance, skincare, tools — verified images only

INSERT INTO products (brand_id, category_id, name, slug, description, short_description, price, compare_at_price, sku, stock_quantity, is_active, is_featured, tags) VALUES
((SELECT id FROM brands WHERE slug='dior-beauty'),(SELECT id FROM categories WHERE slug='eau-de-parfum'),'Miss Dior Blooming Bouquet EDP','miss-dior-edp-v2','A tender floral fragrance capturing femininity and freedom. Peony and rose petals open on a heart of white musks, leaving a trail of soft powdery warmth.','Tender floral EDP — peony, rose, white musk',135.00,NULL,'DIOR-FRG-V2',75,TRUE,TRUE,ARRAY['fragrance','floral','feminine','edp']),
((SELECT id FROM brands WHERE slug='ysl-beauty'),(SELECT id FROM categories WHERE slug='eau-de-parfum'),'Libre Eau de Parfum','ysl-libre-edp-v2','A bold floral musk celebrating freedom. Lavender from Provence meets Moroccan orange blossom, with vanilla and cedarwood. Audacious and modern.','Bold floral musk — lavender, orange blossom, vanilla',142.00,NULL,'YSL-FRG-V2',60,TRUE,TRUE,ARRAY['fragrance','floral','musk','bold','feminine']),
((SELECT id FROM brands WHERE slug='chanel'),(SELECT id FROM categories WHERE slug='eau-de-parfum'),'N5 Eau de Parfum','chanel-no5-edp-v2','The most iconic fragrance in the world since 1921. Over 80 ingredients including ylang ylang, May rose, jasmine and sandalwood in a revolutionary abstract floral aldehyde.','The worlds most iconic fragrance since 1921',195.00,NULL,'CHANEL-FRG-V2',50,TRUE,TRUE,ARRAY['fragrance','floral','iconic','luxury','timeless']),
((SELECT id FROM brands WHERE slug='byredo'),(SELECT id FROM categories WHERE slug='eau-de-parfum'),'Gypsy Water Eau de Parfum','byredo-gypsy-water-v2','Bergamot and lemon open to juniper berries, pine needles and orris, settling on amber, vanilla and sandalwood. Romantic, adventurous and utterly unique.','Adventurous EDP — bergamot, pine, amber, vanilla',220.00,NULL,'BYREDO-FRG-V2',40,TRUE,FALSE,ARRAY['fragrance','woody','amber','unisex','artisan']),
((SELECT id FROM brands WHERE slug='jo-malone'),(SELECT id FROM categories WHERE slug='eau-de-parfum'),'Peony and Blush Suede Cologne','jo-malone-peony-blush-v2','Red apple and peony wrapped in raspberry and suede for an intense feminine scent. A heady bouquet that is fresh, powdery and deeply luxurious.','Intense feminine floral — peony, suede, raspberry',156.00,NULL,'JM-FRG-V2',55,TRUE,FALSE,ARRAY['fragrance','floral','feminine','suede','british']),
((SELECT id FROM brands WHERE slug='ysl-beauty'),(SELECT id FROM categories WHERE slug='eau-de-parfum'),'Black Opium Eau de Parfum','ysl-black-opium-edp-v2','An addictive rock-chic fragrance blending black coffee, vanilla and white flowers. Seductive yet energising — a daring gourmand-floral impossible to resist.','Addictive coffee-vanilla floral EDP',132.00,NULL,'YSL-FRG-V2B',70,TRUE,TRUE,ARRAY['fragrance','gourmand','coffee','vanilla','bold']),
((SELECT id FROM brands WHERE slug='la-mer'),(SELECT id FROM categories WHERE slug='moisturizers'),'Creme de la Mer','la-mer-creme-v2','Miracle Broth moisturiser that heals, renews and transforms skin. Soothes irritation, erases dryness and delivers visible lasting radiance. The worlds most legendary skincare.','The legendary transformative moisturiser',195.00,NULL,'LMR-SKN-V2',70,TRUE,TRUE,ARRAY['moisturiser','luxury','iconic','anti-aging']),
((SELECT id FROM brands WHERE slug='tatcha'),(SELECT id FROM categories WHERE slug='moisturizers'),'The Dewy Skin Cream','tatcha-dewy-skin-cream-v2','Rich cream inspired by Japanese skincare. Hadasei-3 complex, hyaluronic acid and botanical extracts deliver an intense hydration burst for glass-skin radiance.','Japanese-inspired rich plumping moisturiser',68.00,NULL,'TATCHA-SKN-V2',110,TRUE,TRUE,ARRAY['moisturiser','hydrating','japanese','dewy']),
((SELECT id FROM brands WHERE slug='drunk-elephant'),(SELECT id FROM categories WHERE slug='moisturizers'),'Lala Retro Whipped Cream','drunk-elephant-lala-retro-v2','Six African oils and a ceramide complex that replenish the skin barrier and deeply hydrate. Whipped texture absorbs beautifully — skin feels soft, plump and strengthened.','Nutrient-rich whipped moisturiser with African oils',64.00,NULL,'DE-SKN-V2',120,TRUE,FALSE,ARRAY['moisturiser','ceramide','barrier','clean']),
((SELECT id FROM brands WHERE slug='skinceuticals'),(SELECT id FROM categories WHERE slug='serums'),'C E Ferulic Serum','skinceuticals-ce-ferulic-v2','The gold-standard antioxidant serum: 15% vitamin C, 1% vitamin E and 0.5% ferulic acid. Neutralises free radicals, protects against UV damage and improves fine lines, firmness and radiance.','Patented vitamin C antioxidant serum — gold standard',182.00,NULL,'SC-SRM-V2',65,TRUE,TRUE,ARRAY['serum','vitamin-c','antioxidant','anti-aging','brightening']),
((SELECT id FROM brands WHERE slug='the-ordinary'),(SELECT id FROM categories WHERE slug='serums'),'Hyaluronic Acid 2% Plus B5','the-ordinary-ha-v2','Multi-weight hyaluronic acid with vitamin B5 draws moisture to different skin layers for deep lasting hydration and a visibly plumped dewy complexion. Simple, effective, affordable.','Deep multi-weight hydration serum',9.00,NULL,'TO-SRM-V2',400,TRUE,FALSE,ARRAY['serum','hyaluronic-acid','hydrating','affordable','vegan']),
((SELECT id FROM brands WHERE slug='tatcha'),(SELECT id FROM categories WHERE slug='cleansers'),'Pure One Step Camellia Cleansing Oil','tatcha-camellia-oil-v2','Transforms into a milky foam to dissolve makeup, sunscreen and impurities without stripping. Japanese camellia oil and antioxidant green tea leave skin soft, clean and balanced.','Makeup-dissolving Japanese camellia cleansing oil',48.00,NULL,'TATCHA-CLN-V2',130,TRUE,FALSE,ARRAY['cleanser','oil-cleanser','japanese','gentle']),
((SELECT id FROM brands WHERE slug='charlotte-tilbury'),(SELECT id FROM categories WHERE slug='brushes'),'Professional Brush Set','ct-professional-brush-set-v2','Five essential professional brushes — powder, foundation, contour, eye blending and liner — crafted with ultra-soft synthetic fibres and rose-gold handles. The only brush set you will ever need.','5-piece pro brush set with rose-gold handles',220.00,NULL,'CT-TOOL-V2',45,TRUE,TRUE,ARRAY['brushes','professional','set','luxury']),
((SELECT id FROM brands WHERE slug='beautyblender'),(SELECT id FROM categories WHERE slug='brushes'),'Original Beautyblender 3-Pack','beautyblender-3pack-v2','The iconic micro-fine open-cell foam applicator that revolutionised foundation blending. Unique egg shape reaches every contour for a flawless streak-free finish. Three-pack.','The original makeup sponge — 3-pack',35.00,NULL,'BB-TOOL-V2',300,TRUE,TRUE,ARRAY['sponge','applicator','blending','bestseller']),
((SELECT id FROM brands WHERE slug='foreo'),(SELECT id FROM categories WHERE slug='devices'),'LUNA Mini 3 Facial Cleansing Device','foreo-luna-mini-3-v2','Clinically proven silicone cleansing brush removes 99.5% of dirt, oil and makeup in 60 seconds. T-Sonic pulsations provide a deep yet gentle cleanse while anti-aging massage modes firm and lift.','Silicone T-Sonic facial cleanser — clinically proven',119.00,159.00,'FOREO-TOOL-V2',90,TRUE,TRUE,ARRAY['device','cleansing','sonic','anti-aging']),
((SELECT id FROM brands WHERE slug='mac'),(SELECT id FROM categories WHERE slug='brushes'),'168S Large Angled Contour Brush','mac-168s-brush-v2','Professional large angled brush for precise contouring, highlighting and blush. Dense shaped bristles deliver buildable colour and seamless blending for a sculpted natural-looking face.','Pro large angled brush for contour and blush',42.00,NULL,'MAC-TOOL-V2',120,TRUE,FALSE,ARRAY['brush','contour','blush','professional']);

-- Images — only verified working Unsplash photo IDs
INSERT INTO product_images (product_id, url, alt_text, is_primary, sort_order) VALUES
((SELECT id FROM products WHERE sku='DIOR-FRG-V2'),   'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80','Miss Dior EDP',TRUE,1),
((SELECT id FROM products WHERE sku='YSL-FRG-V2'),    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80','YSL Libre EDP',TRUE,1),
((SELECT id FROM products WHERE sku='CHANEL-FRG-V2'), 'https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=600&q=80','Chanel No5 EDP',TRUE,1),
((SELECT id FROM products WHERE sku='BYREDO-FRG-V2'), 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80','Byredo Gypsy Water EDP',TRUE,1),
((SELECT id FROM products WHERE sku='JM-FRG-V2'),     'https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=600&q=80','Jo Malone Peony Blush Suede',TRUE,1),
((SELECT id FROM products WHERE sku='YSL-FRG-V2B'),   'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80','YSL Black Opium EDP',TRUE,1),
((SELECT id FROM products WHERE sku='LMR-SKN-V2'),    'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&q=80','La Mer Creme de la Mer',TRUE,1),
((SELECT id FROM products WHERE sku='TATCHA-SKN-V2'), 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80','Tatcha Dewy Skin Cream',TRUE,1),
((SELECT id FROM products WHERE sku='DE-SKN-V2'),     'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=600&q=80','Drunk Elephant Lala Retro',TRUE,1),
((SELECT id FROM products WHERE sku='SC-SRM-V2'),     'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=600&q=80','Skinceuticals CE Ferulic',TRUE,1),
((SELECT id FROM products WHERE sku='TO-SRM-V2'),     'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80','The Ordinary Hyaluronic Acid',TRUE,1),
((SELECT id FROM products WHERE sku='TATCHA-CLN-V2'), 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80','Tatcha Camellia Cleansing Oil',TRUE,1),
((SELECT id FROM products WHERE sku='CT-TOOL-V2'),    'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80','Charlotte Tilbury Brush Set',TRUE,1),
((SELECT id FROM products WHERE sku='BB-TOOL-V2'),    'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80','Beautyblender 3-Pack',TRUE,1),
((SELECT id FROM products WHERE sku='FOREO-TOOL-V2'), 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&q=80','FOREO LUNA Mini 3',TRUE,1),
((SELECT id FROM products WHERE sku='MAC-TOOL-V2'),   'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80','MAC 168S Contour Brush',TRUE,1);
